### PR TITLE
[AP-2520] Fix smoke test for use case one and two

### PR DESCRIPTION
**Pull request by jsugarman**
## What
Fix smoke test for use case one and two

[Link to story](https://dsdmoj.atlassian.net/browse/AP-2520)

Generate new expected payload for use case one and two and replace
the existing json with them.

Extend testing readme to cover local setup.

## Checklist

Before you ask people to review this PR:

- Tests and rubocop should be passing: `bundle exec rake`
- Github should not be reporting conflicts; you should have recently run `git rebase main`.
- There should be no unnecessary whitespace changes. These make diffs harder to read and conflicts more likely.
- The PR description should say what you changed and why, with a link to the JIRA story.
- You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- You should have checked that the commit messages say why the change was made.
- You should have run `NOCOVERAGE=true rake rswag` to ensure the swagger docs are up-to-date

### CODE REVIEW

**Comment by jsugarman** [comment]
Have tested via swagger docs and one and two pass.

**Comment by jsugarman** [comment]
will add the .env.sample file once this is in as github/circle/git-crypt keeps considering the file to be uncommitted due to gitignore rule issues. If we merge the rule change first I should be able to add it after?!

**Comment by naseberry** [comment]
Why separate files for old use cases?

If smoke test not required for staging, let's remove it in this PR.

👍

**Review by cpjmcquillan — APPROVED** [review]
🎉

**Comment by jsugarman** [comment]
> Member

**Comment by jsugarman** [comment]
> Why separate files for old use cases, can we remove them?
> 
> If smoke test not required for staging, let's remove it in this PR.
> 
> 👍

one step at a time. need to discuss with CB

**Pull request merged**
